# Generated by Django 4.2.14 on 2024-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_person_medicalshopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermedicals',
            name='UniqueId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
