# Generated by Django 4.2.10 on 2024-02-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.statemodel'),
        ),
    ]
