# Generated by Django 4.2.10 on 2024-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='PharmacistEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
