# Generated by Django 4.2.3 on 2024-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_registermedicals_connectmedicals'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermedicals',
            name='UniqueId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
