# Generated by Django 4.2.3 on 2024-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_position_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='temporaryNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
