# Generated by Django 4.2.14 on 2024-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_connectmedicals_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmedicals',
            name='is_request_sended',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
