# Generated by Django 4.2.10 on 2024-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_person_user_alter_person_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newAdmin', models.CharField(max_length=30)),
            ],
        ),
    ]
