# Generated by Django 4.2.3 on 2024-06-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_person_temporaryno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
