# Generated by Django 4.2.10 on 2024-02-20 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_makeusadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeusadmin',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
