# Generated by Django 4.2.3 on 2024-06-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_person_druglicenesenumber1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUsers',
        ),
    ]
