# Generated by Django 4.2.14 on 2024-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_connectmedicals_is_request_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectmedicals',
            name='status_message',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
