# Generated by Django 4.2.3 on 2024-06-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_notification_email_notification_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
