# Generated by Django 4.2.3 on 2024-06-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_addusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectmedicals',
            old_name='attcept_status',
            new_name='accept_status',
        ),
    ]
