# Generated by Django 5.0.6 on 2024-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_notification_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
