# Generated by Django 4.2.3 on 2024-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=15, null=True, unique=True)),
                ('message', models.TextField(default='Notification')),
                ('position', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='position',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Notification'),
        ),
    ]
