# Generated by Django 4.2.13 on 2024-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_addusers_remove_notification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
