# Generated by Django 4.2.3 on 2024-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0010_delete_userloginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invoice_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions related to invoices for this user.', related_name='customuser_invoice_set', to='auth.permission', verbose_name='invoice permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='store_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('manufacturer', 'Manufacturer'), ('pharmacy', 'Pharmacy'), ('medical', 'Medical'), ('user', 'User'), ('others', 'Others')], max_length=50),
        ),
    ]
