# Generated by Django 4.2.3 on 2024-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_invoice_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_permissions',
        ),
        migrations.AddField(
            model_name='makeusadmin',
            name='request_sender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
