# Generated by Django 4.2.9 on 2024-03-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_invoice_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_permissions',
        ),
    ]
