# Generated by Django 4.2.3 on 2024-04-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_notification_delete_makeusadmin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('sender', 'receiver')},
        ),
    ]
