# Generated by Django 4.2.3 on 2024-04-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_attcept',
            field=models.BooleanField(default=False),
        ),
    ]
