# Generated by Django 4.2.3 on 2024-04-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_notification_request_attcept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='request_attcept',
            new_name='falied_request',
        ),
    ]
