# Generated by Django 4.2.3 on 2024-04-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_request_attcept_notification_falied_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='falied_request',
            new_name='failed_request',
        ),
    ]
