# Generated by Django 4.2.3 on 2024-04-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_falied_request_notification_failed_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='failed_request',
        ),
    ]
