# Generated by Django 4.2.3 on 2024-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_notification_failed_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_status',
            field=models.BooleanField(default=True),
        ),
    ]
