# Generated by Django 4.0.10 on 2024-01-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
