# Generated by Django 4.2.3 on 2024-04-06 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(11, 49, 9, 886875)),
        ),
    ]
