# Generated by Django 4.2.3 on 2024-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedinvoice',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modifiedinvoice',
            name='modified_Invoice_number',
            field=models.CharField(max_length=5),
        ),
    ]
