# Generated by Django 4.2.3 on 2024-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpayment',
            name='Bill_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
