# Generated by Django 4.2.14 on 2024-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dl_number1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dl_number2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
