# Generated by Django 5.0.6 on 2024-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0002_alter_deletedinvoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedinvoice',
            name='modified_Invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
