# Generated by Django 4.2.3 on 2024-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0002_invoice_current_time_invoice_today_date_invoice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
