# Generated by Django 4.2.11 on 2024-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0002_trackingpayment_bill_no_alter_invoice_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
