# Generated by Django 4.2.9 on 2024-04-01 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0002_invoice_current_time_invoice_today_date_invoice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(11, 26, 12, 614858)),
        ),
    ]
