# Generated by Django 4.2.10 on 2024-02-13 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0003_alter_invoice_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='today_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
