# Generated by Django 4.2.11 on 2024-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0005_alter_invoice_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
