# Generated by Django 4.2.3 on 2024-06-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0008_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='mail_receiver_position',
        ),
    ]
