# Generated by Django 4.2.3 on 2024-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0009_remove_invitation_mail_receiver_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='mail_receiver_position',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
