# Generated by Django 4.2.9 on 2024-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0009_modifiedinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='csv_field',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='csv_field',
            field=models.TextField(null=True),
        ),
    ]
