# Generated by Django 4.2.3 on 2024-03-20 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0009_modifiedinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='HistoricalInvoice',
        ),
    ]
