# Generated by Django 4.2.3 on 2024-03-20 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0010_invoice_current_time_delete_historicalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(18, 53, 38, 872599)),
        ),
    ]
