# Generated by Django 4.2.3 on 2024-03-20 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0011_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(18, 56, 18, 648801)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='today_date',
            field=models.DateField(default=datetime.date(2024, 3, 20)),
        ),
    ]
