# Generated by Django 4.2.3 on 2024-03-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0012_alter_invoice_current_time_alter_invoice_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(18, 59, 35, 197752)),
        ),
    ]
