# Generated by Django 4.2.3 on 2024-03-20 13:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0013_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(19, 10, 2, 338086)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='today_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
