# Generated by Django 4.2.3 on 2024-03-20 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0014_alter_invoice_current_time_alter_invoice_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(22, 6, 56, 912589)),
        ),
    ]
