# Generated by Django 4.2.3 on 2024-03-22 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0017_alter_invoice_current_time_trackingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedinvoice',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(12, 19, 19, 368936)),
        ),
        migrations.DeleteModel(
            name='TrackingPayment',
        ),
    ]
