# Generated by Django 4.2.3 on 2024-03-22 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0018_alter_deletedinvoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(13, 8, 3, 916946)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modifiedinvoice',
            name='modified_Invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
