# Generated by Django 4.2.3 on 2024-03-25 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0024_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(11, 58, 20, 599525)),
        ),
    ]
