<<<<<<< HEAD
# Generated by Django 4.2.9 on 2024-03-26 05:30
=======
# Generated by Django 4.0.10 on 2024-03-26 10:12
>>>>>>> 88fcb64ea988ec1be319365018bfc63e1bfd912f

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0028_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
<<<<<<< HEAD
            field=models.TimeField(default=datetime.time(10, 59, 59, 524675)),
        ),
    ]

# Generated by Django 4.2.9 on 2024-03-27 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0028_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(12, 16, 46, 204950)),
=======
            field=models.TimeField(default=datetime.time(15, 42, 21, 879177)),
>>>>>>> 88fcb64ea988ec1be319365018bfc63e1bfd912f
        ),
    ]
