# Generated by Django 4.2.9 on 2024-03-26 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invclc', '0029_alter_invoice_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='current_time',
            field=models.TimeField(default=datetime.time(14, 40, 9, 619637)),
        ),
    ]
